import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ ADD INTER
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// ✅ ADD POPPINS
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Mayur Shelke - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${geistSans.variable} ${geistMono.variable} ${inter.variable} ${poppins.variable} `}
    >
      <body className="antialiased">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* ✅ GLOBAL WRAPPER */}
          <div className="border-border mx-auto min-h-screen max-w-3xl border-x px-4">
            {/* HEADER */}
            <Header />

            {/* MAIN CONTENT */}
            <main className="pt-4">{children}</main>

            {/* FOOTER (optional) */}
            {/* <Footer /> */}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
