import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "./pages/header";
import Footer from "./pages/footer/footer-section";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ ADD INTER
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// ✅ ADD POPPINS
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Mayur - A Full Stack web developer",
  description: "Generated by create next app",
  icons: {
    icon: "/IMG-4.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${geistSans.variable} ${geistMono.variable} ${inter.variable} ${poppins.variable} `}
    >
      <body className="antialiased">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* ✅ GLOBAL WRAPPER */}
          <div className="sm:border-border mx-auto min-h-screen max-w-3xl sm:border-x">
            <Header />
            <div className="px-4 sm:px-6 md:px-8">
              {/* HEADER */}

              {/* MAIN CONTENT */}
              <main className="pt-2 sm:pt-4">{children}</main>

              {/* FOOTER (optional) */}
              <Footer />
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
